### ISSUE TITLE
Could I use this with the Neptune 3 Pro?

### ISSUE THREAD

**Issue by kozross** [jerryngm/Neptune-Elegoo3-Klipper#5]
How much would need to change to use this with the Neptune 3 Pro?

**Comment by mygrexit** [comment]
Greet question, would be interested as well!

**Comment by kozross** [comment]
Doesn't matter, I [already fixed this problem myself](https://github.com/Klipper3d/klipper/pull/5965).

**Comment by mygrexit** [comment]
@kozross, was going to link it to you a few minutes ago until I realized that it's your PR. Thanks mate, much appreciated!
